import React, { createContext, useContext, useState, useCallback, useRef } from 'react';
import { getConciergeResponse } from '../services/geminiService';

export type Language = 'en' | 'it' | 'de' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
  isTranslating: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (text: string) => text,
  isTranslating: false,
});

export const useLanguage = () => useContext(LanguageContext);

const LANG_NAMES: Record<Language, string> = {
  en: 'English',
  it: 'Italiano',
  de: 'Deutsch',
  es: 'Español',
  fr: 'Français',
};

const translationCache: Record<string, Record<string, string>> = {};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [translations, setTranslations] = useState<Record<string, string>>({});
  const [isTranslating, setIsTranslating] = useState(false);
  const activeLanguageRef = useRef<Language>('en');

  const setLanguage = useCallback((lang: Language) => {
    if (lang === activeLanguageRef.current) return;
    activeLanguageRef.current = lang;
    setLanguageState(lang);
    if (lang === 'en') { setTranslations({}); return; }
    const cached = translationCache[lang];
    const fallback = getFallbackTranslations(lang);
    const merged = cached ? { ...fallback, ...cached } : fallback;
    translationCache[lang] = merged;
    setTranslations(merged);
  }, []);

  /* ─── Smart t() with auto-translate for missing strings ─── */
  const pendingStringsRef = useRef<Set<string>>(new Set());
  const translateTimerRef = useRef<number | null>(null);

  const translatePending = useCallback(async () => {
    const lang = activeLanguageRef.current;
    if (lang === 'en' || pendingStringsRef.current.size === 0) return;
    const strings = Array.from(pendingStringsRef.current).slice(0, 50);
    pendingStringsRef.current.clear();
    setIsTranslating(true);

    const langName = LANG_NAMES[lang];
    const prompt = `Translate ALL of the following UI texts from English to ${langName}.
Return ONLY a valid JSON object where keys are the exact original English texts and values are the ${langName} translations.
Rules:
- Keep brand names unchanged: "Al Pelmo", "Cadore", "Trevisan", "Tiziano", "Pelmo"
- "Dolomites" should be translated: Italian="Dolomiti", German="Dolomiten", Spanish="Dolomitas"
- Keep proper nouns, dates, numbers, emails, phone numbers, URLs unchanged
- Translate naturally and warmly — this is a luxury hotel website

Texts:
${JSON.stringify(strings)}`;

    try {
      const response = await getConciergeResponse(prompt);
      if (activeLanguageRef.current !== lang) return;   // stale — user switched
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        setTranslations(prev => {
          const merged = { ...prev, ...parsed };
          translationCache[lang] = merged;
          return merged;
        });
      }
    } catch (error) {
      console.error('Smart t() translation error:', error);
    } finally {
      setIsTranslating(false);
    }
  }, []);

  const t = useCallback((text: string): string => {
    if (language === 'en') return text;
    const translated = translations[text];
    if (translated) return translated;

    // Queue untranslated string for batch Gemini translation
    if (text && text.length > 1 && !pendingStringsRef.current.has(text)) {
      pendingStringsRef.current.add(text);
      if (translateTimerRef.current) clearTimeout(translateTimerRef.current);
      translateTimerRef.current = window.setTimeout(() => {
        translatePending();
      }, 800);
    }

    return text;
  }, [language, translations, translatePending]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTranslating }}>
      {children}
    </LanguageContext.Provider>
  );
};

/* ─── Comprehensive fallback translations ─── */
function getFallbackTranslations(lang: Language): Record<string, string> {
  const map: Record<Language, Record<string, string>> = {
    en: {},
    fr: {
      // Nav
      'Rooms': 'Chambres',
      'Wellness': 'Bien-être',
      'Activities': 'Activités',
      'Dining': 'Restauration',
      'Contact': 'Contact',
      // Hero
      'Dolomites': 'Dolomites',
      'Welcome to the': 'Bienvenue dans les',
      'enjoy your stay!': 'profitez de votre séjour !',
      'Compare Seasons': 'Comparer les Saisons',
      'Arrival': 'Arrivée',
      'Departure': 'Départ',
      'Guests': 'Invités',
      'Check Availability': 'Vérifier la Disponibilité',
      'Scroll to explore': 'Faites défiler pour explorer',
      '1 Adult': '1 Adulte',
      '2 Adults': '2 Adultes',
      '3 Adults': '3 Adultes',
      '4 Adults': '4 Adultes',
      '2 Adults, 1 Child': '2 Adultes, 1 Enfant',
      '2 Adults, 2 Children': '2 Adultes, 2 Enfants',
      // Gallery
      'Capturing the Essence': "Capturer l'Essence",
      'THE SOUL OF': "L'ÂME DES",
      'THE DOLOMITES': 'DOLOMITES',
      'Peaks of Wonder': "Sommets d'Émerveillement",
      'The Dolomites, a UNESCO World Heritage site, offer some of the most breathtaking vertical landscapes on Earth.': 'Les Dolomites, site du patrimoine mondial de l\'UNESCO, offrent certains des paysages verticaux les plus époustouflants de la Terre.',
      'Valley Heritage': 'Héritage de la Vallée',
      'Nestled between ancient forests and crystalline lakes, the Cadore valley preserves centuries of authentic Italian mountain culture.': 'Niché entre des forêts ancestrales et des lacs cristallins, la vallée du Cadore préserve des siècles de culture montagnarde italienne authentique.',
      'Winter Magic': 'Magie Hivernale',
      'When snow blankets the peaks, the Dolomites transform into a serene winter paradise of pristine silence and alpine beauty.': 'Quand la neige recouvre les sommets, les Dolomites se transforment en un serein paradis hivernal de silence immaculé et de beauté alpine.',
      // OurJourney
      'Since 1919': 'Depuis 1919',
      'OUR JOURNEY': 'NOTRE VOYAGE',
      'Through Time': 'À Travers le Temps',
      'Over a century of passion, family, and the relentless pursuit of mountain perfection.': 'Plus d\'un siècle de passion, de famille et de quête incessante de la perfection montagnarde.',
      'The Journey Continues': 'Le Voyage Continue',
      'The Beginning': 'Les Débuts',
      'A Dream in the Mountains': 'Un Rêve dans les Montagnes',
      'The Trevisan family opens a small mountain inn in the heart of Cadore — a warm refuge for travelers drawn by the majesty of the Dolomites. What began as a humble guesthouse would become a century-long legacy of Alpine hospitality.': 'La famille Trevisan ouvre une petite auberge de montagne au cœur du Cadore — un refuge chaleureux pour les voyageurs attirés par la majesté des Dolomites. Ce qui commença comme une humble pension deviendrait un héritage centenaire d\'hospitalité alpine.',
      'Post-War Revival': 'Renaissance d\'Après-Guerre',
      'Rising Anew': 'Renaître',
      'After years of turmoil, the hotel is lovingly rebuilt and expanded. A new generation of the Trevisan family welcomes travelers from across Europe, rekindling the warmth and spirit of the original mountain inn.': 'Après des années de tumulte, l\'hôtel est amoureusement reconstruit et agrandi. Une nouvelle génération de la famille Trevisan accueille les voyageurs de toute l\'Europe, ravivant la chaleur et l\'esprit de l\'auberge de montagne originale.',
      'Culinaria dal 1919': 'Culinaria dal 1919',
      'A Table in the Peaks': 'Une Table dans les Sommets',
      'The celebrated Ristorante dal 1919 opens its doors. Mountain heritage meets contemporary refinement — dishes crafted from locally foraged ingredients, paired with the finest regional wines of the Veneto.': 'Le célèbre Ristorante dal 1919 ouvre ses portes. L\'héritage montagnard rencontre le raffinement contemporain — des plats élaborés à partir d\'ingrédients locaux, accompagnés des meilleurs vins régionaux de la Vénétie.',
      'Alpine Wellness': 'Bien-être Alpin',
      'Serenity Above the Clouds': 'Sérénité au-dessus des Nuages',
      'A world-class spa emerges amidst the peaks — panoramic heated infinity pool overlooking Lake Centro Cadore, salt-rock saunas, and Alpine treatments that honor centuries of mountain healing traditions.': 'Un spa de classe mondiale émerge au milieu des sommets — piscine à débordement chauffée panoramique surplombant le Lac Centro Cadore, saunas aux pierres de sel et soins alpins qui honorent des siècles de traditions curatives montagnardes.',
      'A New Chapter': 'Un Nouveau Chapitre',
      'The Future of Tradition': 'L\'Avenir de la Tradition',
      'Modern sustainability meets timeless hospitality. The next generation of the Trevisan family carries the torch — with a deep commitment to the land, the community, and every guest who walks through our doors.': 'La durabilité moderne rencontre l\'hospitalité intemporelle. La nouvelle génération de la famille Trevisan porte le flambeau — avec un profond engagement envers la terre, la communauté et chaque hôte qui franchit nos portes.',
      // Quote
      '"Where the peaks touch the soul."': '"Là où les sommets touchent l\'âme."',
      'Gildo Trevisan, Founder Since 1919': 'Gildo Trevisan, Fondateur depuis 1919',
      // Rooms
      'The Collection': 'La Collection',
      'Our Rooms &': 'Nos Chambres &',
      'Suites': 'Suites',
      'Each room is a carefully curated retreat — blending local materials, panoramic views, and mountain tranquility.': 'Chaque chambre est une retraite soigneusement conçue — mêlant matériaux locaux, vues panoramiques et tranquillité montagnarde.',
      'Classic Alpine Room': 'Chambre Alpine Classique',
      'Authentic Comfort': 'Confort Authentique',
      'Elegantly furnished with local larch wood, offering a cozy atmosphere and a view of the surrounding forest and mountains.': 'Élégamment meublée en bois de mélèze local, offrant une atmosphère chaleureuse et une vue sur la forêt et les montagnes environnantes.',
      'Lake View Junior Suite': 'Junior Suite Vue Lac',
      'Panoramic Bliss': 'Bonheur Panoramique',
      'Spacious suites with floor-to-ceiling windows overlooking the valley and the hillside charm of Pieve di Cadore.': 'Suites spacieuses avec des baies vitrées du sol au plafond surplombant la vallée et le charme de Pieve di Cadore.',
      'Pelmo Presidential Penthouse': 'Penthouse Présidentiel Pelmo',
      'Peak Luxury': 'Luxe des Sommets',
      'The pinnacle of luxury. A multi-level suite featuring iconic framed views of the snowy Dolomites peaks directly from your window.': 'Le summum du luxe. Une suite sur plusieurs niveaux avec des vues iconiques encadrées sur les sommets enneigés des Dolomites directement depuis votre fenêtre.',
      'From': 'À partir de',
      '/ night': '/ nuit',
      'Size': 'Taille',
      'Mountain View': 'Vue Montagne',
      'Fireplace': 'Cheminée',
      'Larch Wood': 'Bois de Mélèze',
      'Valley Views': 'Vue Vallée',
      'Private Terrace': 'Terrasse Privée',
      'Rain Shower': 'Douche à l\'Italienne',
      'Dolomites Panorama': 'Panorama Dolomites',
      'Private Sauna': 'Sauna Privé',
      'Two Levels': 'Deux Niveaux',
      'Reserve Room': 'Réserver la Chambre',
      // Wellness
      'Rest, Restore &': 'Repos, Restauration &',
      'Rebalance': 'Rééquilibre',
      'A holistic retreat rooted in the natural elements of the Dolomites — where silence, warmth, and altitude restore mind and body.': 'Une retraite holistique enracinée dans les éléments naturels des Dolomites — où le silence, la chaleur et l\'altitude restaurent l\'esprit et le corps.',
      'Mountain Resonance': 'Résonance Montagnarde',
      'Our concept is rooted in the "Path of the Elements" — a sensorially guided journey that synchronizes your heart rate with the rhythm of the Dolomites.': 'Notre concept est enraciné dans le "Chemin des Éléments" — un parcours guidé sensoriellement qui synchronise votre rythme cardiaque avec celui des Dolomites.',
      'Our Treatments': 'Nos Soins',
      'Alpine Aromatherapy': 'Aromathérapie Alpine',
      'Essential oils from local pine and wildflower meadows.': 'Huiles essentielles de pins locaux et de prairies de fleurs sauvages.',
      'Dolomite Stone Ritual': 'Rituel de Pierre Dolomitique',
      'Hot stone therapy using native Dolomite mineral rock.': 'Thérapie aux pierres chaudes utilisant la roche minérale dolomitique.',
      'Thermal Water Circuit': 'Circuit d\'Eaux Thermales',
      'Hot and cold pools fed by natural mountain springs.': 'Piscines chaudes et froides alimentées par des sources naturelles de montagne.',
      'Mountain Meditation': 'Méditation de Montagne',
      'Guided sessions on our panoramic larch balconies.': 'Séances guidées sur nos balcons panoramiques en mélèze.',
      'Sensory Fragments': 'Fragments Sensoriels',
      'Glimpses of our century-old wellness heritage.': 'Aperçus de notre patrimoine centenaire de bien-être.',
      'Thermal Pool': 'Piscine Thermale',
      'Sauna Suite': 'Suite Sauna',
      'Relaxation Room': 'Salle de Relaxation',
      'Alpine Garden': 'Jardin Alpin',
      'Steam Bath': 'Bain de Vapeur',
      'Treatment Room': 'Salle de Soins',
      // Dining
      'Gastronomy': 'Gastronomie',
      'Ristorante': 'Ristorante',
      'Four generations of the Trevisan family have shaped a kitchen that honors the rugged elegance of the Dolomites.': 'Quatre générations de la famille Trevisan ont façonné une cuisine qui honore l\'élégance brute des Dolomites.',
      'The Art of High Altitude': 'L\'Art de la Haute Altitude',
      'Under the stewardship of the Trevisan family for four generations, Ristorante 1919 is a beacon of Cadore hospitality. Our kitchen honors the rugged elegance of the Dolomites.': 'Sous la direction de la famille Trevisan depuis quatre générations, le Ristorante 1919 est un phare de l\'hospitalité cadorine. Notre cuisine honore l\'élégance brute des Dolomites.',
      'Under the stewardship of the Trevisan family for three generations, Ristorante 1919 is a beacon of Cadore hospitality. Our kitchen honors the rugged elegance of the Dolomites.': 'Sous la direction de la famille Trevisan depuis trois générations, le Ristorante 1919 est un phare de l\'hospitalité cadorine. Notre cuisine honore l\'élégance brute des Dolomites.',
      'Local Cuisine Expert': 'Experte en Cuisine Locale',
      'Executive Chef': 'Chef Exécutif',
      'The Menu': 'Le Menu',
      'Locally sourced ingredients at 878m altitude with terroir integrity in every dish.': 'Ingrédients locaux à 878m d\'altitude avec l\'intégrité du terroir dans chaque plat.',
      'Locally sourced ingredients at 1,200m altitude—terroir integrity in every dish.': 'Ingrédients locaux à 1 200m d\'altitude — l\'intégrité du terroir dans chaque plat.',
      'Mountain Terroir': 'Terroir de Montagne',
      'Game and mountain herbs from the Zoldo valley.': 'Gibier et herbes de montagne de la vallée de Zoldo.',
      'Cadore Flavors': 'Saveurs du Cadore',
      "Hand-crafted pasta following nonna's legacy.": 'Pâtes artisanales selon la tradition de la nonna.',
      'Alpine Deli': 'Délicatessen Alpine',
      'The finest selection of local cheeses and cured meats.': 'La plus fine sélection de fromages et charcuteries locaux.',
      'Symphony Sweet': 'Symphonie Sucrée',
      'A sweet end with forest-inspired desserts.': 'Une fin sucrée avec des desserts inspirés de la forêt.',
      'View Details': 'Voir les Détails',
      'Selected': 'Sélectionné',
      'Chef': 'Chef',
      'Moha Boulmane': 'Moha Boulmane',
      'Gildo Trevisan': 'Gildo Trevisan',
      "Today's Special": 'Plat du Jour',
      'Cellar': 'Cave',
      '450+ Vintages': '450+ Millésimes',
      'Wild Boar Ragú': 'Ragú de Sanglier',
      // Contact
      'Get in': 'Prenez',
      'Touch': 'Contact',
      "We'd love to hear from you. Reach out for reservations, special requests, or simply to say hello.": 'Nous serions ravis de vous entendre. Contactez-nous pour des réservations, des demandes spéciales ou simplement pour dire bonjour.',
      'Direct Channels': 'Contacts Directs',
      'Call Us': 'Appelez-nous',
      'Email': 'E-mail',
      'Location': 'Emplacement',
      'Getting Here': 'Comment Venir',
      'Scenic Drive': 'Route Panoramique',
      'Hiking Start': 'Départ Randonnée',
      'Airport': 'Aéroport',
      'By Car': 'En Voiture',
      'Send a Message': 'Envoyer un Message',
      'Each stay is tailored by our concierge.': 'Chaque séjour est personnalisé par notre concierge.',
      'Name': 'Nom',
      'Your name': 'Votre nom',
      'Message': 'Message',
      'Describe your ideal retreat...': 'Décrivez votre séjour idéal...',
      'Send Message': 'Envoyer le Message',
      'Thank you!': 'Merci !',
      "We'll be in touch shortly. Arrivederci!": 'Nous vous recontacterons bientôt. Arrivederci !',
      'Find Us': 'Nous Trouver',
      'Get Directions': 'Itinéraire',
      // WhatToDo
      'WHAT TO DO': 'QUE FAIRE',
      'In the Dolomites': 'Dans les Dolomites',
      'Adventures Await': 'Les Aventures vous Attendent',
      'From summit trails to still waters, every day brings a new way to fall in love with the mountains.': 'Des sentiers de sommets aux eaux calmes, chaque jour apporte une nouvelle façon de tomber amoureux des montagnes.',
      'Ask Gildo': 'Demandez à Gildo',
      'Powered by AI · Ask me anything': 'Propulsé par l\'IA · Posez-moi n\'importe quelle question',
      'Ask about activities, difficulty level, weather...': 'Renseignez-vous sur les activités, le niveau de difficulté, la météo...',
      'Hiking': 'Randonnée',
      'Trails for Every Soul': 'Des Sentiers pour Chaque Âme',
      'Explore over 200 km of marked trails through pristine Dolomite landscapes — from gentle lakeside walks around Centro Cadore to challenging summit routes up Monte Pelmo and the Cadini di Misurina. Every step reveals another breathtaking panorama.': 'Explorez plus de 200 km de sentiers balisés à travers des paysages dolomitiques préservés — des douces promenades au bord du lac de Centro Cadore aux sentiers exigeants vers le Monte Pelmo et les Cadini di Misurina. Chaque pas révèle un autre panorama époustouflant.',
      'Skiing & Snowboard': 'Ski & Snowboard',
      'Powder Paradise': 'Paradis de la Poudreuse',
      "Hit the slopes of the Dolomiti Superski — one of the world's largest ski areas with 1,200 km of runs. From the gentle pistes of Auronzo to the legendary Cortina d'Ampezzo, world-class skiing is just minutes away from the hotel.": "Dévalez les pistes du Dolomiti Superski — l'un des plus grands domaines skiables au monde avec 1 200 km de pistes. Des pentes douces d'Auronzo à la légendaire Cortina d'Ampezzo, le ski de classe mondiale est à quelques minutes de l'hôtel.",
      'Mountain Biking': 'VTT',
      'Ride the Peaks': 'Pédalez les Sommets',
      "From adrenaline-pumping downhill trails to scenic gravel routes along the old Dolomites railway, Cadore is a cyclist's dream. Rent e-bikes or join guided tours through ancient forests and alpine meadows.": 'Des sentiers de descente pleins d\'adrénaline aux routes panoramiques le long de l\'ancienne voie ferrée des Dolomites, le Cadore est le rêve de tout cycliste. Louez des vélos électriques ou rejoignez des visites guidées à travers des forêts ancestrales et des prairies alpines.',
      'Lake Adventures': 'Aventures au Lac',
      'Serenity on Water': 'Sérénité sur l\'Eau',
      'Paddle across the emerald waters of Lake Centro Cadore, try stand-up paddleboarding at sunrise, or simply relax on the lakeshore with a book and the reflection of the mountains. Pure tranquility.': 'Pagayez sur les eaux émeraude du Lac Centro Cadore, essayez le stand-up paddle au lever du soleil, ou détendez-vous simplement au bord du lac avec un livre et le reflet des montagnes. Pure tranquillité.',
      'Mountain Hub': 'Mountain Hub',
      'Your Base Camp': 'Votre Camp de Base',
      'Our in-house Mountain Hub is your starting point for any adventure. Expert local guides, equipment rental, trail maps, and curated excursion packages — everything you need for an unforgettable Dolomite experience.': 'Notre Mountain Hub est votre point de départ pour toute aventure. Guides locaux experts, location d\'équipement, cartes de sentiers et forfaits d\'excursions — tout ce dont vous avez besoin pour une expérience inoubliable dans les Dolomites.',
      'Art & Culture': 'Art & Culture',
      'Birthplace of Tiziano': 'Lieu de Naissance de Titien',
      'Pieve di Cadore is the birthplace of the great Renaissance master Tiziano Vecellio. Visit the Tiziano Museum, explore centuries-old churches, and wander through villages where Venetian and Ladin culture intertwine.': 'Pieve di Cadore est le lieu de naissance du grand maître de la Renaissance Tiziano Vecellio. Visitez le Musée Titien, explorez des églises centenaires et flânez dans des villages où les cultures vénitienne et ladine s\'entrelacent.',
      'Spring · Summer · Autumn': 'Printemps · Été · Automne',
      'December – April': 'Décembre – Avril',
      'May – October': 'Mai – Octobre',
      'June – September': 'Juin – Septembre',
      'Year Round': 'Toute l\'Année',
      'All Levels': 'Tous Niveaux',
      'Easy': 'Facile',
      'Beginner to Expert': 'Débutant à Expert',
      'Moderate to Advanced': 'Modéré à Avancé',
      'Easy family hike with kids': 'Randonnée familiale facile avec enfants',
      'Best ski slopes for beginners': 'Meilleures pistes de ski pour débutants',
      'Mountain biking trails nearby': 'Sentiers VTT à proximité',
      'Rainy day activities': 'Activités par temps de pluie',
      'Romantic sunset viewpoints': 'Points de vue romantiques au coucher du soleil',
      // Footer
      'Social': 'Réseaux',
      'Contact Info': 'Coordonnées',
      'Partners': 'Partenaires',
      '© 2024 Hotel Al Pelmo Ristorante. All rights reserved.': '© 2024 Hotel Al Pelmo Ristorante. Tous droits réservés.',
      'Designed for the Soul of the Dolomites': 'Conçu pour l\'Âme des Dolomites',
    },
    it: {
      // Nav
      'Rooms': 'Camere',
      'Wellness': 'Benessere',
      'Activities': 'Attività',
      'Dining': 'Ristorante',
      'Contact': 'Contatti',
      // Hero
      'Nature Sound Off': 'Suoni Natura Disattivati',
      'Nature Sound On': 'Suoni Natura Attivati',
      'Dolomites': 'Dolomiti',
      'Welcome to the': 'Benvenuti nelle',
      'enjoy your stay!': 'buon soggiorno!',
      'Compare Seasons': 'Confronta le stagioni',
      'Arrival': 'Arrivo',
      'Departure': 'Partenza',
      'Guests': 'Ospiti',
      'Check Availability': 'Verifica disponibilità',
      'Scroll to explore': 'Scorri per esplorare',
      '1 Adult': '1 Adulto',
      '2 Adults': '2 Adulti',
      '3 Adults': '3 Adulti',
      '4 Adults': '4 Adulti',
      '2 Adults, 1 Child': '2 Adulti, 1 Bambino',
      '2 Adults, 2 Children': '2 Adulti, 2 Bambini',
      // Gallery
      'Capturing the Essence': "Catturare l'essenza",
      'THE SOUL OF': "L'ANIMA DELLE",
      'THE DOLOMITES': 'DOLOMITI',
      'Peaks of Wonder': 'Vette della Meraviglia',
      'The Dolomites, a UNESCO World Heritage site, offer some of the most breathtaking vertical landscapes on Earth.': 'Le Dolomiti, patrimonio UNESCO, offrono alcuni dei paesaggi verticali più spettacolari della Terra.',
      'Valley Heritage': 'Eredità della Valle',
      'Nestled between ancient forests and crystalline lakes, the Cadore valley preserves centuries of authentic Italian mountain culture.': 'Tra antiche foreste e laghi cristallini, la valle del Cadore conserva secoli di autentica cultura montana italiana.',
      'Winter Magic': 'Magia Invernale',
      'When snow blankets the peaks, the Dolomites transform into a serene winter paradise of pristine silence and alpine beauty.': 'Quando la neve copre le vette, le Dolomiti si trasformano in un sereno paradiso invernale di silenzio e bellezza alpina.',
      // OurJourney
      'Since 1919': 'Dal 1919',
      'OUR JOURNEY': 'IL NOSTRO VIAGGIO',
      'Through Time': 'Nel Tempo',
      'Over a century of passion, family, and the relentless pursuit of mountain perfection.': 'Oltre un secolo di passione, famiglia e instancabile ricerca della perfezione montana.',
      'The Journey Continues': 'Il Viaggio Continua',
      'The Beginning': "L'Inizio",
      'A Dream in the Mountains': 'Un Sogno in Montagna',
      'The Trevisan family opens a small mountain inn in the heart of Cadore — a warm refuge for travelers drawn by the majesty of the Dolomites. What began as a humble guesthouse would become a century-long legacy of Alpine hospitality.': 'La famiglia Trevisan apre una piccola locanda di montagna nel cuore del Cadore — un caldo rifugio per i viaggiatori attratti dalla maestosità delle Dolomiti. Quello che iniziò come una modesta pensione sarebbe diventato un\'eredità secolare di ospitalità alpina.',
      'Post-War Revival': 'Rinascita Postbellica',
      'Rising Anew': 'Rinascere',
      'After years of turmoil, the hotel is lovingly rebuilt and expanded. A new generation of the Trevisan family welcomes travelers from across Europe, rekindling the warmth and spirit of the original mountain inn.': 'Dopo anni di tumulto, l\'hotel è amorevolmente ricostruito e ampliato. Una nuova generazione della famiglia Trevisan accoglie viaggiatori da tutta Europa, riaccendendo il calore e lo spirito della locanda di montagna originale.',
      'Culinaria dal 1919': 'Culinaria dal 1919',
      'A Table in the Peaks': 'Una Tavola tra le Vette',
      'The celebrated Ristorante dal 1919 opens its doors. Mountain heritage meets contemporary refinement — dishes crafted from locally foraged ingredients, paired with the finest regional wines of the Veneto.': 'Il celebre Ristorante dal 1919 apre le sue porte. L\'eredità montana incontra la raffinatezza contemporanea — piatti preparati con ingredienti locali, abbinati ai migliori vini regionali del Veneto.',
      'Alpine Wellness': 'Benessere Alpino',
      'Serenity Above the Clouds': 'Serenità Sopra le Nuvole',
      'A world-class spa emerges amidst the peaks — panoramic heated infinity pool overlooking Lake Centro Cadore, salt-rock saunas, and Alpine treatments that honor centuries of mountain healing traditions.': 'Una spa di livello mondiale emerge tra le vette — piscina a sfioro riscaldata panoramica con vista sul Lago di Centro Cadore, saune di sale, e trattamenti alpini che onorano secoli di tradizioni curative montane.',
      'A New Chapter': 'Un Nuovo Capitolo',
      'The Future of Tradition': 'Il Futuro della Tradizione',
      'Modern sustainability meets timeless hospitality. The next generation of the Trevisan family carries the torch — with a deep commitment to the land, the community, and every guest who walks through our doors.': 'La sostenibilità moderna incontra l\'ospitalità senza tempo. La nuova generazione della famiglia Trevisan porta avanti la fiaccola — con un profondo impegno verso la terra, la comunità e ogni ospite che varca le nostre porte.',
      // Quote
      '"Where the peaks touch the soul."': '"Dove le vette toccano l\'anima."',
      'Gildo Trevisan, Founder Since 1919': 'Gildo Trevisan, Fondatore dal 1919',
      // Rooms
      'The Collection': 'La Collezione',
      'Our Rooms &': 'Le Nostre Camere e',
      'Suites': 'Suite',
      'Each room is a carefully curated retreat — blending local materials, panoramic views, and mountain tranquility.': 'Ogni camera è un rifugio curato — materiali locali, viste panoramiche e tranquillità montana.',
      'Classic Alpine Room': 'Camera Alpina Classica',
      'Authentic Comfort': 'Comfort Autentico',
      'Elegantly furnished with local larch wood, offering a cozy atmosphere and a view of the surrounding forest and mountains.': 'Arredata con eleganza in legno di larice locale, con un\'atmosfera accogliente e vista sul bosco e sulle montagne circostanti.',
      'Lake View Junior Suite': 'Junior Suite Vista Lago',
      'Panoramic Bliss': 'Panorama Incantevole',
      'Spacious suites with floor-to-ceiling windows overlooking the valley and the hillside charm of Pieve di Cadore.': 'Spaziose suite con finestre dal pavimento al soffitto che si affacciano sulla valle e sul fascino collinare di Pieve di Cadore.',
      'Pelmo Presidential Penthouse': 'Attico Presidenziale Pelmo',
      'Peak Luxury': 'Lusso in Vetta',
      'The pinnacle of luxury. A multi-level suite featuring iconic framed views of the snowy Dolomites peaks directly from your window.': 'L\'apice del lusso. Una suite su più livelli con iconiche viste incorniciate sulle vette innevate delle Dolomiti direttamente dalla finestra.',
      'From': 'Da',
      '/ night': '/ notte',
      'Size': 'Dimensione',
      'Mountain View': 'Vista Montagna',
      'Fireplace': 'Camino',
      'Larch Wood': 'Legno di Larice',
      'Valley Views': 'Vista Valle',
      'Private Terrace': 'Terrazza Privata',
      'Rain Shower': 'Doccia a Pioggia',
      'Dolomites Panorama': 'Panorama Dolomiti',
      'Private Sauna': 'Sauna Privata',
      'Two Levels': 'Due Livelli',
      'Reserve Room': 'Prenota Camera',
      // Wellness
      'Rest, Restore &': 'Riposo, Ristoro e',
      'Rebalance': 'Riequilibrio',
      'A holistic retreat rooted in the natural elements of the Dolomites — where silence, warmth, and altitude restore mind and body.': 'Un rifugio olistico radicato negli elementi naturali delle Dolomiti — dove silenzio, calore e altitudine rigenerano mente e corpo.',
      'Mountain Resonance': 'Risonanza Montana',
      'Our concept is rooted in the "Path of the Elements" — a sensorially guided journey that synchronizes your heart rate with the rhythm of the Dolomites.': 'Il nostro concetto è radicato nel "Sentiero degli Elementi" — un percorso guidato sensorialmente che sincronizza il battito cardiaco con il ritmo delle Dolomiti.',
      'Our Treatments': 'I Nostri Trattamenti',
      'Alpine Aromatherapy': 'Aromaterapia Alpina',
      'Essential oils from local pine and wildflower meadows.': 'Oli essenziali da pini locali e prati di fiori selvatici.',
      'Dolomite Stone Ritual': 'Rituale Pietra Dolomitica',
      'Hot stone therapy using native Dolomite mineral rock.': 'Trattamento con pietre calde utilizzando roccia minerale dolomitica.',
      'Thermal Water Circuit': 'Circuito Acque Termali',
      'Hot and cold pools fed by natural mountain springs.': 'Piscine calde e fredde alimentate da sorgenti naturali di montagna.',
      'Mountain Meditation': 'Meditazione Montana',
      'Guided sessions on our panoramic larch balconies.': 'Sessioni guidate sui nostri balconi panoramici in larice.',
      'Sensory Fragments': 'Frammenti Sensoriali',
      'Glimpses of our century-old wellness heritage.': 'Scorci del nostro patrimonio di benessere centenario.',
      'Thermal Pool': 'Piscina Termale',
      'Sauna Suite': 'Suite Sauna',
      'Relaxation Room': 'Sala Relax',
      'Alpine Garden': 'Giardino Alpino',
      'Steam Bath': 'Bagno di Vapore',
      'Treatment Room': 'Sala Trattamenti',
      // Dining
      'Gastronomy': 'Gastronomia',
      'Ristorante': 'Ristorante',
      'Four generations of the Trevisan family have shaped a kitchen that honors the rugged elegance of the Dolomites.': 'Quattro generazioni della famiglia Trevisan hanno plasmato una cucina che onora la ruvida eleganza delle Dolomiti.',
      'The Art of High Altitude': "L'Arte dell'Alta Quota",
      'Under the stewardship of the Trevisan family for four generations, Ristorante 1919 is a beacon of Cadore hospitality. Our kitchen honors the rugged elegance of the Dolomites.': 'Sotto la guida della famiglia Trevisan da quattro generazioni, il Ristorante 1919 è un faro di ospitalità cadorina. La nostra cucina onora la ruvida eleganza delle Dolomiti.',
      'Executive Chef': 'Chef Esecutivo',
      'The Menu': 'Il Menu',
      'Locally sourced ingredients at 1,200m altitude—terroir integrity in every dish.': "Ingredienti locali a 1.200m — l'integrità del terroir in ogni piatto.",
      'Mountain Terroir': 'Terroir di Montagna',
      'Game and mountain herbs from the Zoldo valley.': 'Selvaggina ed erbe di montagna dalla Val di Zoldo.',
      'Cadore Flavors': 'Sapori del Cadore',
      "Hand-crafted pasta following nonna's legacy.": 'Pasta fatta a mano seguendo la tradizione della nonna.',
      'Alpine Deli': 'Gastronomia Alpina',
      'The finest selection of local cheeses and cured meats.': 'La più fine selezione di formaggi e salumi locali.',
      'Symphony Sweet': 'Dolce Sinfonia',
      'A sweet end with forest-inspired desserts.': 'Un dolce finale con dessert ispirati al bosco.',
      'View Details': 'Dettagli',
      'Selected': 'Selezionato',
      'Chef': 'Chef',
      'Gildo Trevisan': 'Gildo Trevisan',
      "Today's Special": 'Piatto del Giorno',
      'Cellar': 'Cantina',
      '450+ Vintages': '450+ Annate',
      'Wild Boar Ragú': 'Ragù di Cinghiale',
      // Contact
      'Get in': 'Mettiti in',
      'Touch': 'Contatto',
      "We'd love to hear from you. Reach out for reservations, special requests, or simply to say hello.": 'Ci farebbe piacere sentirti. Scrivici per prenotazioni, richieste speciali, o anche solo per un saluto.',
      'Direct Channels': 'Contatti Diretti',
      'Call Us': 'Chiamaci',
      'Email': 'Email',
      'Location': 'Posizione',
      'Getting Here': 'Come Arrivare',
      'Scenic Drive': 'Percorso Panoramico',
      'Hiking Start': 'Partenza Escursione',
      'Airport': 'Aeroporto',
      'By Car': 'In Auto',
      'Send a Message': 'Invia un Messaggio',
      'Each stay is tailored by our concierge.': 'Ogni soggiorno è personalizzato dal nostro concierge.',
      'Name': 'Nome',
      'Your name': 'Il tuo nome',
      'Message': 'Messaggio',
      'Describe your ideal retreat...': 'Descrivi il tuo soggiorno ideale...',
      'Send Message': 'Invia Messaggio',
      'Thank you!': 'Grazie!',
      "We'll be in touch shortly. Arrivederci!": 'Ti contatteremo a breve. Arrivederci!',
      // WhatToDo
      'WHAT TO DO': 'COSA FARE',
      'In the Dolomites': 'Nelle Dolomiti',
      'Adventures Await': 'Avventure vi Attendono',
      'From summit trails to still waters, every day brings a new way to fall in love with the mountains.': 'Dai sentieri di vetta alle acque tranquille, ogni giorno porta un nuovo modo di innamorarsi delle montagne.',
      'Ask Gildo': 'Parla con Gildo',
      'Powered by AI · Ask me anything': 'Powered by AI · Chiedimi tutto',
      'Ask about activities, difficulty level, weather...': 'Chiedi di attività, difficoltà, meteo...',
      'Hiking': 'Escursionismo',
      'Trails for Every Soul': 'Sentieri per Ogni Anima',
      'Explore over 200 km of marked trails through pristine Dolomite landscapes — from gentle lakeside walks around Centro Cadore to challenging summit routes up Monte Pelmo and the Cadini di Misurina. Every step reveals another breathtaking panorama.': 'Esplora oltre 200 km di sentieri segnalati attraverso paesaggi dolomitici incontaminati — da dolci passeggiate lungo il lago di Centro Cadore a impegnativi percorsi di vetta sul Monte Pelmo e i Cadini di Misurina. Ogni passo svela un altro panorama mozzafiato.',
      'Skiing & Snowboard': 'Sci e Snowboard',
      'Powder Paradise': 'Paradiso della Neve',
      "Hit the slopes of the Dolomiti Superski — one of the world's largest ski areas with 1,200 km of runs. From the gentle pistes of Auronzo to the legendary Cortina d'Ampezzo, world-class skiing is just minutes away from the hotel.": "Le piste del Dolomiti Superski — uno dei più grandi comprensori sciistici al mondo con 1.200 km di piste. Dalle dolci discese di Auronzo alla leggendaria Cortina d'Ampezzo, lo sci di classe mondiale è a pochi minuti dall'hotel.",
      'Mountain Biking': 'Mountain Bike',
      'Ride the Peaks': 'Cavalca le Vette',
      "From adrenaline-pumping downhill trails to scenic gravel routes along the old Dolomites railway, Cadore is a cyclist's dream. Rent e-bikes or join guided tours through ancient forests and alpine meadows.": 'Dai percorsi in discesa carichi di adrenalina alle panoramiche strade sterrate lungo la vecchia ferrovia delle Dolomiti, il Cadore è il sogno di ogni ciclista. Noleggia e-bike o unisciti a tour guidati attraverso foreste antiche e prati alpini.',
      'Lake Adventures': 'Avventure al Lago',
      'Serenity on Water': "Serenità sull'Acqua",
      'Paddle across the emerald waters of Lake Centro Cadore, try stand-up paddleboarding at sunrise, or simply relax on the lakeshore with a book and the reflection of the mountains. Pure tranquility.': 'Pagaia sulle acque smeraldine del Lago di Centro Cadore, prova lo stand-up paddleboarding all\'alba, o semplicemente rilassati sulla riva del lago con un libro e il riflesso delle montagne. Pura tranquillità.',
      'Mountain Hub': 'Mountain Hub',
      'Your Base Camp': 'Il Tuo Campo Base',
      'Our in-house Mountain Hub is your starting point for any adventure. Expert local guides, equipment rental, trail maps, and curated excursion packages — everything you need for an unforgettable Dolomite experience.': 'Il nostro Mountain Hub interno è il punto di partenza per ogni avventura. Guide locali esperte, noleggio attrezzature, mappe dei sentieri e pacchetti escursionistici curati — tutto il necessario per un\'indimenticabile esperienza dolomitica.',
      'Art & Culture': 'Arte e Cultura',
      'Birthplace of Tiziano': 'Luogo Natale di Tiziano',
      'Pieve di Cadore is the birthplace of the great Renaissance master Tiziano Vecellio. Visit the Tiziano Museum, explore centuries-old churches, and wander through villages where Venetian and Ladin culture intertwine.': 'Pieve di Cadore è il luogo natale del grande maestro rinascimentale Tiziano Vecellio. Visita il Museo di Tiziano, esplora chiese plurisecolari e passeggia tra i villaggi dove la cultura veneziana e ladina si intrecciano.',
      'Spring · Summer · Autumn': 'Primavera · Estate · Autunno',
      'December – April': 'Dicembre – Aprile',
      'May – October': 'Maggio – Ottobre',
      'June – September': 'Giugno – Settembre',
      'Year Round': 'Tutto l\'Anno',
      'All Levels': 'Tutti i Livelli',
      'Easy': 'Facile',
      'Beginner to Expert': 'Principiante ad Esperto',
      'Moderate to Advanced': 'Moderato ad Avanzato',
      'Easy family hike with kids': 'Escursione facile per famiglie con bambini',
      'Best ski slopes for beginners': 'Le migliori piste da sci per principianti',
      'Mountain biking trails nearby': 'Percorsi in mountain bike nelle vicinanze',
      'Rainy day activities': 'Attività per i giorni di pioggia',
      'Romantic sunset viewpoints': 'Punti panoramici romantici al tramonto',
      // Footer
      'Social': 'Social',
      'Contact Info': 'Info Contatti',
      'Partners': 'Partner',
      '© 2024 Hotel Al Pelmo Ristorante. All rights reserved.': '© 2024 Hotel Al Pelmo Ristorante. Tutti i diritti riservati.',
      'Designed for the Soul of the Dolomites': "Progettato per l'Anima delle Dolomiti",
    },
    de: {
      // Nav
      'Rooms': 'Zimmer',
      'Wellness': 'Wellness',
      'Activities': 'Aktivitäten',
      'Dining': 'Restaurant',
      'Contact': 'Kontakt',
      // Hero
      'Dolomites': 'Dolomiten',
      'Welcome to the': 'Willkommen in den',
      'enjoy your stay!': 'genießen Sie Ihren Aufenthalt!',
      'Compare Seasons': 'Jahreszeiten vergleichen',
      'Arrival': 'Anreise',
      'Departure': 'Abreise',
      'Guests': 'Gäste',
      'Check Availability': 'Verfügbarkeit prüfen',
      'Scroll to explore': 'Scrollen zum Entdecken',
      '1 Adult': '1 Erwachsener',
      '2 Adults': '2 Erwachsene',
      '3 Adults': '3 Erwachsene',
      '4 Adults': '4 Erwachsene',
      '2 Adults, 1 Child': '2 Erwachsene, 1 Kind',
      '2 Adults, 2 Children': '2 Erwachsene, 2 Kinder',
      // Gallery
      'Capturing the Essence': 'Die Essenz einfangen',
      'THE SOUL OF': 'DIE SEELE DER',
      'THE DOLOMITES': 'DOLOMITEN',
      'Peaks of Wonder': 'Gipfel des Staunens',
      'The Dolomites, a UNESCO World Heritage site, offer some of the most breathtaking vertical landscapes on Earth.': 'Die Dolomiten, UNESCO-Weltkulturerbe, bieten einige der atemberaubendsten vertikalen Landschaften der Erde.',
      'Valley Heritage': 'Erbe des Tals',
      'Nestled between ancient forests and crystalline lakes, the Cadore valley preserves centuries of authentic Italian mountain culture.': 'Eingebettet zwischen uralten Wäldern und kristallklaren Seen bewahrt das Cadore-Tal Jahrhunderte authentischer italienischer Bergkultur.',
      'Winter Magic': 'Winterzauber',
      'When snow blankets the peaks, the Dolomites transform into a serene winter paradise of pristine silence and alpine beauty.': 'Wenn Schnee die Gipfel bedeckt, verwandeln sich die Dolomiten in ein ruhiges Winterparadies aus unberührter Stille und alpiner Schönheit.',
      // OurJourney
      'Since 1919': 'Seit 1919',
      'OUR JOURNEY': 'UNSERE REISE',
      'Through Time': 'Durch die Zeit',
      'Over a century of passion, family, and the relentless pursuit of mountain perfection.': 'Über ein Jahrhundert voller Leidenschaft, Familie und dem unermüdlichen Streben nach bergiger Perfektion.',
      'The Journey Continues': 'Die Reise geht weiter',
      'The Beginning': 'Der Anfang',
      'A Dream in the Mountains': 'Ein Traum in den Bergen',
      'The Trevisan family opens a small mountain inn in the heart of Cadore — a warm refuge for travelers drawn by the majesty of the Dolomites. What began as a humble guesthouse would become a century-long legacy of Alpine hospitality.': 'Die Familie Trevisan eröffnet ein kleines Berggasthaus im Herzen des Cadore — ein warmer Zufluchtsort für Reisende, die von der Majestät der Dolomiten angezogen werden. Was als bescheidene Pension begann, wurde zu einem jahrhundertelangen Erbe alpiner Gastfreundschaft.',
      'Post-War Revival': 'Nachkriegszeit',
      'Rising Anew': 'Neuanfang',
      'After years of turmoil, the hotel is lovingly rebuilt and expanded. A new generation of the Trevisan family welcomes travelers from across Europe, rekindling the warmth and spirit of the original mountain inn.': 'Nach Jahren des Umbruchs wird das Hotel liebevoll wieder aufgebaut und erweitert. Eine neue Generation der Familie Trevisan heißt Reisende aus ganz Europa willkommen und entfacht die Wärme und den Geist des ursprünglichen Berggasthauses neu.',
      'Culinaria dal 1919': 'Culinaria dal 1919',
      'A Table in the Peaks': 'Ein Tisch in den Gipfeln',
      'The celebrated Ristorante dal 1919 opens its doors. Mountain heritage meets contemporary refinement — dishes crafted from locally foraged ingredients, paired with the finest regional wines of the Veneto.': 'Das gefeierte Ristorante dal 1919 öffnet seine Türen. Bergerbe trifft auf zeitgenössische Raffinesse — Gerichte aus lokal gesammelten Zutaten, begleitet von den besten regionalen Weinen des Veneto.',
      'Alpine Wellness': 'Alpines Wellness',
      'Serenity Above the Clouds': 'Ruhe über den Wolken',
      'A world-class spa emerges amidst the peaks — panoramic heated infinity pool overlooking Lake Centro Cadore, salt-rock saunas, and Alpine treatments that honor centuries of mountain healing traditions.': 'Ein erstklassiges Spa inmitten der Gipfel — beheizter Panorama-Infinitypool mit Blick auf den Lago di Centro Cadore, Salzstein-Saunen und alpine Behandlungen, die Jahrhunderte bergiger Heiltraditionen ehren.',
      'A New Chapter': 'Ein neues Kapitel',
      'The Future of Tradition': 'Die Zukunft der Tradition',
      'Modern sustainability meets timeless hospitality. The next generation of the Trevisan family carries the torch — with a deep commitment to the land, the community, and every guest who walks through our doors.': 'Moderne Nachhaltigkeit trifft auf zeitlose Gastfreundschaft. Die nächste Generation der Familie Trevisan trägt die Fackel weiter — mit einem tiefen Engagement für das Land, die Gemeinschaft und jeden Gast, der durch unsere Türen tritt.',
      // Quote
      '"Where the peaks touch the soul."': '"Wo die Gipfel die Seele berühren."',
      'Gildo Trevisan, Founder Since 1919': 'Gildo Trevisan, Gründer seit 1919',
      // Rooms
      'The Collection': 'Die Kollektion',
      'Our Rooms &': 'Unsere Zimmer &',
      'Suites': 'Suiten',
      'Each room is a carefully curated retreat — blending local materials, panoramic views, and mountain tranquility.': 'Jedes Zimmer ist ein sorgfältig kuratierter Rückzugsort — eine Mischung aus lokalen Materialien, Panoramablicken und bergiger Ruhe.',
      'Classic Alpine Room': 'Klassisches Alpenzimmer',
      'Authentic Comfort': 'Authentischer Komfort',
      'Elegantly furnished with local larch wood, offering a cozy atmosphere and a view of the surrounding forest and mountains.': 'Elegant eingerichtet mit lokalem Lärchenholz, mit gemütlicher Atmosphäre und Blick auf den umliegenden Wald und die Berge.',
      'Lake View Junior Suite': 'Junior Suite mit Seeblick',
      'Panoramic Bliss': 'Panoramisches Glück',
      'Spacious suites with floor-to-ceiling windows overlooking the valley and the hillside charm of Pieve di Cadore.': 'Geräumige Suiten mit raumhohen Fenstern mit Blick auf das Tal und den Charme von Pieve di Cadore.',
      'Pelmo Presidential Penthouse': 'Pelmo Präsidenten-Penthouse',
      'Peak Luxury': 'Gipfel-Luxus',
      'The pinnacle of luxury. A multi-level suite featuring iconic framed views of the snowy Dolomites peaks directly from your window.': 'Der Gipfel des Luxus. Eine mehrstöckige Suite mit ikonischen gerahmten Ausblicken auf die verschneiten Dolomitengipfel direkt vom Fenster.',
      'From': 'Ab',
      '/ night': '/ Nacht',
      'Size': 'Größe',
      'Mountain View': 'Bergblick',
      'Fireplace': 'Kamin',
      'Larch Wood': 'Lärchenholz',
      'Valley Views': 'Talblick',
      'Private Terrace': 'Private Terrasse',
      'Rain Shower': 'Regendusche',
      'Dolomites Panorama': 'Dolomiten-Panorama',
      'Private Sauna': 'Private Sauna',
      'Two Levels': 'Zwei Ebenen',
      'Reserve Room': 'Zimmer reservieren',
      // Wellness
      'Rest, Restore &': 'Ruhe, Erholung &',
      'Rebalance': 'Neubalance',
      'A holistic retreat rooted in the natural elements of the Dolomites — where silence, warmth, and altitude restore mind and body.': 'Ein ganzheitlicher Rückzugsort, verwurzelt in den natürlichen Elementen der Dolomiten — wo Stille, Wärme und Höhe Geist und Körper wiederherstellen.',
      'Mountain Resonance': 'Bergresonanz',
      'Our concept is rooted in the "Path of the Elements" — a sensorially guided journey that synchronizes your heart rate with the rhythm of the Dolomites.': 'Unser Konzept basiert auf dem "Pfad der Elemente" — eine sensorisch geführte Reise, die Ihren Herzschlag mit dem Rhythmus der Dolomiten synchronisiert.',
      'Our Treatments': 'Unsere Behandlungen',
      'Alpine Aromatherapy': 'Alpine Aromatherapie',
      'Essential oils from local pine and wildflower meadows.': 'Ätherische Öle aus lokalen Kiefern und Wildblumenwiesen.',
      'Dolomite Stone Ritual': 'Dolomitstein-Ritual',
      'Hot stone therapy using native Dolomite mineral rock.': 'Hot-Stone-Therapie mit einheimischem Dolomit-Mineralstein.',
      'Thermal Water Circuit': 'Thermalwasser-Kreislauf',
      'Hot and cold pools fed by natural mountain springs.': 'Warm- und Kaltbecken, gespeist von natürlichen Bergquellen.',
      'Mountain Meditation': 'Bergmeditation',
      'Guided sessions on our panoramic larch balconies.': 'Geführte Sitzungen auf unseren Panorama-Lärchenbalkonen.',
      'Sensory Fragments': 'Sensorische Fragmente',
      'Glimpses of our century-old wellness heritage.': 'Einblicke in unser jahrhundertealtes Wellness-Erbe.',
      'Thermal Pool': 'Thermalbad',
      'Sauna Suite': 'Sauna-Suite',
      'Relaxation Room': 'Ruheraum',
      'Alpine Garden': 'Alpiner Garten',
      'Steam Bath': 'Dampfbad',
      'Treatment Room': 'Behandlungsraum',
      // Dining
      'Gastronomy': 'Gastronomie',
      'Ristorante': 'Ristorante',
      'Four generations of the Trevisan family have shaped a kitchen that honors the rugged elegance of the Dolomites.': 'Vier Generationen der Familie Trevisan haben eine Küche geprägt, die die raue Eleganz der Dolomiten ehrt.',
      'The Art of High Altitude': 'Die Kunst der Höhe',
      'Under the stewardship of the Trevisan family for four generations, Ristorante 1919 is a beacon of Cadore hospitality. Our kitchen honors the rugged elegance of the Dolomites.': 'Unter der Leitung der Familie Trevisan seit vier Generationen ist das Ristorante 1919 ein Leuchtturm der Cadore-Gastfreundschaft. Unsere Küche ehrt die raue Eleganz der Dolomiten.',
      'Executive Chef': 'Küchenchef',
      'The Menu': 'Die Speisekarte',
      'Locally sourced ingredients at 1,200m altitude—terroir integrity in every dish.': 'Lokal bezogene Zutaten auf 1.200m Höhe — Terroir-Integrität in jedem Gericht.',
      'Mountain Terroir': 'Berg-Terroir',
      'Game and mountain herbs from the Zoldo valley.': 'Wild und Bergkräuter aus dem Zoldotal.',
      'Cadore Flavors': 'Cadore-Geschmack',
      "Hand-crafted pasta following nonna's legacy.": 'Handgemachte Pasta nach Nonnas Tradition.',
      'Alpine Deli': 'Alpine Delikatessen',
      'The finest selection of local cheeses and cured meats.': 'Die feinste Auswahl an lokalen Käse- und Wurstwaren.',
      'Symphony Sweet': 'Süße Symphonie',
      'A sweet end with forest-inspired desserts.': 'Ein süßes Ende mit waldinspierten Desserts.',
      'View Details': 'Details ansehen',
      'Selected': 'Ausgewählt',
      'Chef': 'Chef',
      'Gildo Trevisan': 'Gildo Trevisan',
      "Today's Special": 'Tagesgericht',
      'Cellar': 'Weinkeller',
      '450+ Vintages': '450+ Jahrgänge',
      'Wild Boar Ragú': 'Wildschwein-Ragú',
      // Contact
      'Get in': 'Treten Sie in',
      'Touch': 'Kontakt',
      "We'd love to hear from you. Reach out for reservations, special requests, or simply to say hello.": 'Wir freuen uns auf Ihre Nachricht. Kontaktieren Sie uns für Reservierungen, besondere Wünsche oder einfach um Hallo zu sagen.',
      'Direct Channels': 'Direkter Kontakt',
      'Call Us': 'Rufen Sie uns an',
      'Email': 'E-Mail',
      'Location': 'Standort',
      'Getting Here': 'Anreise',
      'Scenic Drive': 'Panoramafahrt',
      'Hiking Start': 'Wanderstart',
      'Airport': 'Flughafen',
      'By Car': 'Mit dem Auto',
      'Send a Message': 'Nachricht senden',
      'Each stay is tailored by our concierge.': 'Jeder Aufenthalt wird von unserem Concierge maßgeschneidert.',
      'Name': 'Name',
      'Your name': 'Ihr Name',
      'Message': 'Nachricht',
      'Describe your ideal retreat...': 'Beschreiben Sie Ihren idealen Aufenthalt...',
      'Send Message': 'Nachricht senden',
      'Thank you!': 'Danke!',
      "We'll be in touch shortly. Arrivederci!": 'Wir melden uns in Kürze. Arrivederci!',
      // WhatToDo
      'WHAT TO DO': 'WAS TUN',
      'In the Dolomites': 'In den Dolomiten',
      'Adventures Await': 'Abenteuer erwarten Sie',
      'From summit trails to still waters, every day brings a new way to fall in love with the mountains.': 'Von Gipfelpfaden bis zu stillen Gewässern bringt jeder Tag eine neue Art, sich in die Berge zu verlieben.',
      'Ask Gildo': 'Frag Gildo',
      'Powered by AI · Ask me anything': 'KI-gestützt · Fragen Sie mich alles',
      'Ask about activities, difficulty level, weather...': 'Fragen Sie nach Aktivitäten, Schwierigkeitsgrad, Wetter...',
      'Hiking': 'Wandern',
      'Trails for Every Soul': 'Wanderwege für jede Seele',
      'Explore over 200 km of marked trails through pristine Dolomite landscapes — from gentle lakeside walks around Centro Cadore to challenging summit routes up Monte Pelmo and the Cadini di Misurina. Every step reveals another breathtaking panorama.': 'Entdecken Sie über 200 km markierte Wanderwege durch unberührte Dolomitenlandschaften — von sanften Seeuferspaziergängen um Centro Cadore bis zu anspruchsvollen Gipfelrouten auf den Monte Pelmo und die Cadini di Misurina. Jeder Schritt enthüllt ein weiteres atemberaubendes Panorama.',
      'Skiing & Snowboard': 'Ski & Snowboard',
      'Powder Paradise': 'Pulverschnee-Paradies',
      "Hit the slopes of the Dolomiti Superski — one of the world's largest ski areas with 1,200 km of runs. From the gentle pistes of Auronzo to the legendary Cortina d'Ampezzo, world-class skiing is just minutes away from the hotel.": "Die Pisten des Dolomiti Superski — eines der größten Skigebiete der Welt mit 1.200 km Abfahrten. Von den sanften Pisten von Auronzo bis zum legendären Cortina d'Ampezzo ist Weltklasse-Skifahren nur Minuten vom Hotel entfernt.",
      'Mountain Biking': 'Mountainbiken',
      'Ride the Peaks': 'Die Gipfel erradeln',
      "From adrenaline-pumping downhill trails to scenic gravel routes along the old Dolomites railway, Cadore is a cyclist's dream. Rent e-bikes or join guided tours through ancient forests and alpine meadows.": 'Von adrenalingeladenen Downhill-Trails bis hin zu malerischen Schotterwegen entlang der alten Dolomitenbahn — Cadore ist ein Radfahrertraum. Mieten Sie E-Bikes oder nehmen Sie an geführten Touren durch uralte Wälder und Almwiesen teil.',
      'Lake Adventures': 'See-Abenteuer',
      'Serenity on Water': 'Ruhe auf dem Wasser',
      'Paddle across the emerald waters of Lake Centro Cadore, try stand-up paddleboarding at sunrise, or simply relax on the lakeshore with a book and the reflection of the mountains. Pure tranquility.': 'Paddeln Sie über die smaragdgrünen Gewässer des Lago di Centro Cadore, versuchen Sie Stand-up-Paddleboarding bei Sonnenaufgang, oder entspannen Sie einfach am Seeufer mit einem Buch und dem Spiegelbild der Berge. Pure Ruhe.',
      'Mountain Hub': 'Mountain Hub',
      'Your Base Camp': 'Ihr Basislager',
      'Our in-house Mountain Hub is your starting point for any adventure. Expert local guides, equipment rental, trail maps, and curated excursion packages — everything you need for an unforgettable Dolomite experience.': 'Unser hauseigener Mountain Hub ist Ihr Ausgangspunkt für jedes Abenteuer. Erfahrene lokale Führer, Ausrüstungsverleih, Wanderkarten und kuratierte Ausflugspakete — alles, was Sie für ein unvergessliches Dolomitenerlebnis brauchen.',
      'Art & Culture': 'Kunst & Kultur',
      'Birthplace of Tiziano': 'Geburtsort von Tiziano',
      'Pieve di Cadore is the birthplace of the great Renaissance master Tiziano Vecellio. Visit the Tiziano Museum, explore centuries-old churches, and wander through villages where Venetian and Ladin culture intertwine.': 'Pieve di Cadore ist der Geburtsort des großen Renaissancemeisters Tiziano Vecellio. Besuchen Sie das Tiziano-Museum, erkunden Sie jahrhundertealte Kirchen und wandern Sie durch Dörfer, in denen venezianische und ladinische Kultur verschmelzen.',
      'Spring · Summer · Autumn': 'Frühling · Sommer · Herbst',
      'December – April': 'Dezember – April',
      'May – October': 'Mai – Oktober',
      'June – September': 'Juni – September',
      'Year Round': 'Ganzjährig',
      'All Levels': 'Alle Niveaus',
      'Easy': 'Leicht',
      'Beginner to Expert': 'Anfänger bis Experte',
      'Moderate to Advanced': 'Mittel bis Fortgeschritten',
      'Easy family hike with kids': 'Leichte Familienwanderung mit Kindern',
      'Best ski slopes for beginners': 'Beste Skipisten für Anfänger',
      'Mountain biking trails nearby': 'Mountainbike-Strecken in der Nähe',
      'Rainy day activities': 'Aktivitäten bei Regen',
      'Romantic sunset viewpoints': 'Romantische Aussichtspunkte zum Sonnenuntergang',
      // Footer
      'Social': 'Social',
      'Contact Info': 'Kontaktinfo',
      'Partners': 'Partner',
      '© 2024 Hotel Al Pelmo Ristorante. All rights reserved.': '© 2024 Hotel Al Pelmo Ristorante. Alle Rechte vorbehalten.',
      'Designed for the Soul of the Dolomites': 'Gestaltet für die Seele der Dolomiten',
    },
    es: {
      // Nav
      'Rooms': 'Habitaciones',
      'Wellness': 'Bienestar',
      'Activities': 'Actividades',
      'Dining': 'Restaurante',
      'Contact': 'Contacto',
      // Hero
      'Dolomites': 'Dolomitas',
      'Welcome to the': 'Bienvenido a los',
      'enjoy your stay!': '¡disfruta tu estancia!',
      'Compare Seasons': 'Comparar estaciones',
      'Arrival': 'Llegada',
      'Departure': 'Salida',
      'Guests': 'Huéspedes',
      'Check Availability': 'Comprobar disponibilidad',
      'Scroll to explore': 'Desplázate para explorar',
      '1 Adult': '1 Adulto',
      '2 Adults': '2 Adultos',
      '3 Adults': '3 Adultos',
      '4 Adults': '4 Adultos',
      '2 Adults, 1 Child': '2 Adultos, 1 Niño',
      '2 Adults, 2 Children': '2 Adultos, 2 Niños',
      // Gallery
      'Capturing the Essence': 'Capturando la Esencia',
      'THE SOUL OF': 'EL ALMA DE LAS',
      'THE DOLOMITES': 'DOLOMITAS',
      'Peaks of Wonder': 'Cumbres del Asombro',
      'The Dolomites, a UNESCO World Heritage site, offer some of the most breathtaking vertical landscapes on Earth.': 'Las Dolomitas, Patrimonio de la Humanidad de la UNESCO, ofrecen algunos de los paisajes verticales más impresionantes de la Tierra.',
      'Valley Heritage': 'Herencia del Valle',
      'Nestled between ancient forests and crystalline lakes, the Cadore valley preserves centuries of authentic Italian mountain culture.': 'Enclavado entre bosques ancestrales y lagos cristalinos, el valle del Cadore preserva siglos de auténtica cultura montañesa italiana.',
      'Winter Magic': 'Magia Invernal',
      'When snow blankets the peaks, the Dolomites transform into a serene winter paradise of pristine silence and alpine beauty.': 'Cuando la nieve cubre las cumbres, las Dolomitas se transforman en un sereno paraíso invernal de silencio prístino y belleza alpina.',
      // OurJourney
      'Since 1919': 'Desde 1919',
      'OUR JOURNEY': 'NUESTRO VIAJE',
      'Through Time': 'A Través del Tiempo',
      'Over a century of passion, family, and the relentless pursuit of mountain perfection.': 'Más de un siglo de pasión, familia y la búsqueda incansable de la perfección montana.',
      'The Journey Continues': 'El Viaje Continúa',
      'The Beginning': 'El Comienzo',
      'A Dream in the Mountains': 'Un Sueño en las Montañas',
      'The Trevisan family opens a small mountain inn in the heart of Cadore — a warm refuge for travelers drawn by the majesty of the Dolomites. What began as a humble guesthouse would become a century-long legacy of Alpine hospitality.': 'La familia Trevisan abre una pequeña posada de montaña en el corazón del Cadore — un cálido refugio para viajeros atraídos por la majestuosidad de las Dolomitas. Lo que comenzó como una humilde pensión se convertiría en un legado centenario de hospitalidad alpina.',
      'Post-War Revival': 'Resurgimiento Postguerra',
      'Rising Anew': 'Renacer',
      'After years of turmoil, the hotel is lovingly rebuilt and expanded. A new generation of the Trevisan family welcomes travelers from across Europe, rekindling the warmth and spirit of the original mountain inn.': 'Tras años de adversidad, el hotel es amorosamente reconstruido y ampliado. Una nueva generación de la familia Trevisan da la bienvenida a viajeros de toda Europa, reavivando el calor y el espíritu de la posada original.',
      'Culinaria dal 1919': 'Culinaria dal 1919',
      'A Table in the Peaks': 'Una Mesa en las Cumbres',
      'The celebrated Ristorante dal 1919 opens its doors. Mountain heritage meets contemporary refinement — dishes crafted from locally foraged ingredients, paired with the finest regional wines of the Veneto.': 'El célebre Ristorante dal 1919 abre sus puertas. La herencia montañesa se encuentra con el refinamiento contemporáneo — platos elaborados con ingredientes locales, maridados con los mejores vinos regionales del Veneto.',
      'Alpine Wellness': 'Bienestar Alpino',
      'Serenity Above the Clouds': 'Serenidad sobre las Nubes',
      'A world-class spa emerges amidst the peaks — panoramic heated infinity pool overlooking Lake Centro Cadore, salt-rock saunas, and Alpine treatments that honor centuries of mountain healing traditions.': 'Un spa de clase mundial emerge entre las cumbres — piscina infinita climatizada con vistas al Lago di Centro Cadore, saunas de roca salina, y tratamientos alpinos que honran siglos de tradiciones curativas de montaña.',
      'A New Chapter': 'Un Nuevo Capítulo',
      'The Future of Tradition': 'El Futuro de la Tradición',
      'Modern sustainability meets timeless hospitality. The next generation of the Trevisan family carries the torch — with a deep commitment to the land, the community, and every guest who walks through our doors.': 'La sostenibilidad moderna se encuentra con la hospitalidad atemporal. La nueva generación de la familia Trevisan porta la antorcha — con un profundo compromiso con la tierra, la comunidad y cada huésped que cruza nuestras puertas.',
      // Quote
      '"Where the peaks touch the soul."': '"Donde las cumbres tocan el alma."',
      'Gildo Trevisan, Founder Since 1919': 'Gildo Trevisan, Fundador desde 1919',
      // Rooms
      'The Collection': 'La Colección',
      'Our Rooms &': 'Nuestras Habitaciones y',
      'Suites': 'Suites',
      'Each room is a carefully curated retreat — blending local materials, panoramic views, and mountain tranquility.': 'Cada habitación es un retiro cuidadosamente diseñado — combinando materiales locales, vistas panorámicas y tranquilidad montañesa.',
      'Classic Alpine Room': 'Habitación Alpina Clásica',
      'Authentic Comfort': 'Confort Auténtico',
      'Elegantly furnished with local larch wood, offering a cozy atmosphere and a view of the surrounding forest and mountains.': 'Elegantemente amueblada con madera de alerce local, ofreciendo una atmósfera acogedora y vistas al bosque y las montañas circundantes.',
      'Lake View Junior Suite': 'Junior Suite Vista al Lago',
      'Panoramic Bliss': 'Dicha Panorámica',
      'Spacious suites with floor-to-ceiling windows overlooking the valley and the hillside charm of Pieve di Cadore.': 'Amplias suites con ventanales de piso a techo con vistas al valle y al encanto de Pieve di Cadore.',
      'Pelmo Presidential Penthouse': 'Ático Presidencial Pelmo',
      'Peak Luxury': 'Lujo en la Cumbre',
      'The pinnacle of luxury. A multi-level suite featuring iconic framed views of the snowy Dolomites peaks directly from your window.': 'La cúspide del lujo. Una suite en varios niveles con icónicas vistas enmarcadas de las cumbres nevadas de las Dolomitas directamente desde tu ventana.',
      'From': 'Desde',
      '/ night': '/ noche',
      'Size': 'Tamaño',
      'Mountain View': 'Vista a la Montaña',
      'Fireplace': 'Chimenea',
      'Larch Wood': 'Madera de Alerce',
      'Valley Views': 'Vistas al Valle',
      'Private Terrace': 'Terraza Privada',
      'Rain Shower': 'Ducha de Lluvia',
      'Dolomites Panorama': 'Panorama Dolomitas',
      'Private Sauna': 'Sauna Privada',
      'Two Levels': 'Dos Niveles',
      'Reserve Room': 'Reservar Habitación',
      // Wellness
      'Rest, Restore &': 'Descanso, Restauración y',
      'Rebalance': 'Reequilibrio',
      'A holistic retreat rooted in the natural elements of the Dolomites — where silence, warmth, and altitude restore mind and body.': 'Un retiro holístico enraizado en los elementos naturales de las Dolomitas — donde el silencio, la calidez y la altitud restauran mente y cuerpo.',
      'Mountain Resonance': 'Resonancia Montañesa',
      'Our concept is rooted in the "Path of the Elements" — a sensorially guided journey that synchronizes your heart rate with the rhythm of the Dolomites.': 'Nuestro concepto está enraizado en el "Camino de los Elementos" — un recorrido guiado sensorialmente que sincroniza tu ritmo cardíaco con el ritmo de las Dolomitas.',
      'Our Treatments': 'Nuestros Tratamientos',
      'Alpine Aromatherapy': 'Aromaterapia Alpina',
      'Essential oils from local pine and wildflower meadows.': 'Aceites esenciales de pinos locales y praderas de flores silvestres.',
      'Dolomite Stone Ritual': 'Ritual de Piedra Dolomítica',
      'Hot stone therapy using native Dolomite mineral rock.': 'Terapia de piedras calientes con roca mineral dolomítica.',
      'Thermal Water Circuit': 'Circuito de Aguas Termales',
      'Hot and cold pools fed by natural mountain springs.': 'Piscinas frías y calientes alimentadas por manantiales naturales de montaña.',
      'Mountain Meditation': 'Meditación de Montaña',
      'Guided sessions on our panoramic larch balconies.': 'Sesiones guiadas en nuestros balcones panorámicos de alerce.',
      'Sensory Fragments': 'Fragmentos Sensoriales',
      'Glimpses of our century-old wellness heritage.': 'Destellos de nuestro patrimonio centenario de bienestar.',
      'Thermal Pool': 'Piscina Termal',
      'Sauna Suite': 'Suite Sauna',
      'Relaxation Room': 'Sala de Relajación',
      'Alpine Garden': 'Jardín Alpino',
      'Steam Bath': 'Baño de Vapor',
      'Treatment Room': 'Sala de Tratamientos',
      // Dining
      'Gastronomy': 'Gastronomía',
      'Ristorante': 'Ristorante',
      'Four generations of the Trevisan family have shaped a kitchen that honors the rugged elegance of the Dolomites.': 'Cuatro generaciones de la familia Trevisan han forjado una cocina que honra la ruda elegancia de las Dolomitas.',
      'The Art of High Altitude': 'El Arte de la Altura',
      'Under the stewardship of the Trevisan family for four generations, Ristorante 1919 is a beacon of Cadore hospitality. Our kitchen honors the rugged elegance of the Dolomites.': 'Bajo la dirección de la familia Trevisan durante cuatro generaciones, el Ristorante 1919 es un faro de hospitalidad cadorina. Nuestra cocina honra la ruda elegancia de las Dolomitas.',
      'Executive Chef': 'Chef Ejecutivo',
      'The Menu': 'El Menú',
      'Locally sourced ingredients at 1,200m altitude—terroir integrity in every dish.': 'Ingredientes locales a 1.200m de altitud — integridad del terroir en cada plato.',
      'Mountain Terroir': 'Terroir de Montaña',
      'Game and mountain herbs from the Zoldo valley.': 'Caza y hierbas de montaña del Valle de Zoldo.',
      'Cadore Flavors': 'Sabores del Cadore',
      "Hand-crafted pasta following nonna's legacy.": 'Pasta artesanal siguiendo la tradición de la nonna.',
      'Alpine Deli': 'Delicatessen Alpina',
      'The finest selection of local cheeses and cured meats.': 'La más fina selección de quesos y embutidos locales.',
      'Symphony Sweet': 'Sinfonía Dulce',
      'A sweet end with forest-inspired desserts.': 'Un dulce final con postres inspirados en el bosque.',
      'View Details': 'Ver Detalles',
      'Selected': 'Seleccionado',
      'Chef': 'Chef',
      'Gildo Trevisan': 'Gildo Trevisan',
      "Today's Special": 'Plato del Día',
      'Cellar': 'Bodega',
      '450+ Vintages': '450+ Cosechas',
      'Wild Boar Ragú': 'Ragú de Jabalí',
      // Contact
      'Get in': 'Ponte en',
      'Touch': 'Contacto',
      "We'd love to hear from you. Reach out for reservations, special requests, or simply to say hello.": 'Nos encantaría saber de ti. Contáctanos para reservas, solicitudes especiales o simplemente para saludar.',
      'Direct Channels': 'Canales Directos',
      'Call Us': 'Llámanos',
      'Email': 'Correo',
      'Location': 'Ubicación',
      'Getting Here': 'Cómo Llegar',
      'Scenic Drive': 'Ruta Panorámica',
      'Hiking Start': 'Inicio Senderismo',
      'Airport': 'Aeropuerto',
      'By Car': 'En Coche',
      'Send a Message': 'Enviar un Mensaje',
      'Each stay is tailored by our concierge.': 'Cada estancia es personalizada por nuestro conserje.',
      'Name': 'Nombre',
      'Your name': 'Tu nombre',
      'Message': 'Mensaje',
      'Describe your ideal retreat...': 'Describe tu estancia ideal...',
      'Send Message': 'Enviar Mensaje',
      'Thank you!': '¡Gracias!',
      "We'll be in touch shortly. Arrivederci!": 'Nos pondremos en contacto pronto. ¡Arrivederci!',
      // WhatToDo
      'WHAT TO DO': 'QUÉ HACER',
      'In the Dolomites': 'En las Dolomitas',
      'Adventures Await': 'Aventuras te esperan',
      'From summit trails to still waters, every day brings a new way to fall in love with the mountains.': 'De senderos de cumbre a aguas tranquilas, cada día trae una nueva forma de enamorarse de las montañas.',
      'Ask Gildo': 'Pregunta a Gildo',
      'Powered by AI · Ask me anything': 'Impulsado por IA · Pregúntame lo que sea',
      'Ask about activities, difficulty level, weather...': 'Pregunta sobre actividades, nivel de dificultad, clima...',
      'Hiking': 'Senderismo',
      'Trails for Every Soul': 'Senderos para Cada Alma',
      'Explore over 200 km of marked trails through pristine Dolomite landscapes — from gentle lakeside walks around Centro Cadore to challenging summit routes up Monte Pelmo and the Cadini di Misurina. Every step reveals another breathtaking panorama.': 'Explora más de 200 km de senderos señalizados a través de paisajes dolomíticos prístinos — desde suaves paseos junto al lago de Centro Cadore hasta desafiantes rutas de cumbre hacia el Monte Pelmo y los Cadini di Misurina. Cada paso revela otro panorama impresionante.',
      'Skiing & Snowboard': 'Esquí y Snowboard',
      'Powder Paradise': 'Paraíso de la Nieve',
      "Hit the slopes of the Dolomiti Superski — one of the world's largest ski areas with 1,200 km of runs. From the gentle pistes of Auronzo to the legendary Cortina d'Ampezzo, world-class skiing is just minutes away from the hotel.": "Las pistas del Dolomiti Superski — una de las áreas de esquí más grandes del mundo con 1.200 km de pistas. Desde las suaves pistas de Auronzo hasta la legendaria Cortina d'Ampezzo, el esquí de clase mundial está a pocos minutos del hotel.",
      'Mountain Biking': 'Ciclismo de Montaña',
      'Ride the Peaks': 'Pedalea las Cumbres',
      "From adrenaline-pumping downhill trails to scenic gravel routes along the old Dolomites railway, Cadore is a cyclist's dream. Rent e-bikes or join guided tours through ancient forests and alpine meadows.": 'Desde emocionantes senderos de descenso hasta rutas panorámicas de grava a lo largo de la antigua vía de las Dolomitas, Cadore es el sueño de todo ciclista. Alquila e-bikes o únete a tours guiados por bosques ancestrales y praderas alpinas.',
      'Lake Adventures': 'Aventuras en el Lago',
      'Serenity on Water': 'Serenidad en el Agua',
      'Paddle across the emerald waters of Lake Centro Cadore, try stand-up paddleboarding at sunrise, or simply relax on the lakeshore with a book and the reflection of the mountains. Pure tranquility.': 'Rema sobre las aguas esmeraldas del Lago di Centro Cadore, prueba el stand-up paddleboarding al amanecer, o simplemente relájate en la orilla con un libro y el reflejo de las montañas. Pura tranquilidad.',
      'Mountain Hub': 'Mountain Hub',
      'Your Base Camp': 'Tu Campo Base',
      'Our in-house Mountain Hub is your starting point for any adventure. Expert local guides, equipment rental, trail maps, and curated excursion packages — everything you need for an unforgettable Dolomite experience.': 'Nuestro Mountain Hub interno es tu punto de partida para cualquier aventura. Guías locales expertos, alquiler de equipos, mapas de senderos y paquetes de excursiones curados — todo lo que necesitas para una experiencia inolvidable en las Dolomitas.',
      'Art & Culture': 'Arte y Cultura',
      'Birthplace of Tiziano': 'Cuna de Tiziano',
      'Pieve di Cadore is the birthplace of the great Renaissance master Tiziano Vecellio. Visit the Tiziano Museum, explore centuries-old churches, and wander through villages where Venetian and Ladin culture intertwine.': 'Pieve di Cadore es la cuna del gran maestro renacentista Tiziano Vecellio. Visita el Museo de Tiziano, explora iglesias centenarias y pasea por pueblos donde la cultura veneciana y ladina se entrelazan.',
      'Spring · Summer · Autumn': 'Primavera · Verano · Otoño',
      'December – April': 'Diciembre – Abril',
      'May – October': 'Mayo – Octubre',
      'June – September': 'Junio – Septiembre',
      'Year Round': 'Todo el Año',
      'All Levels': 'Todos los Niveles',
      'Easy': 'Fácil',
      'Beginner to Expert': 'Principiante a Experto',
      'Moderate to Advanced': 'Moderado a Avanzado',
      'Easy family hike with kids': 'Excursión familiar fácil con niños',
      'Best ski slopes for beginners': 'Las mejores pistas de esquí para principiantes',
      'Mountain biking trails nearby': 'Rutas de ciclismo de montaña cercanas',
      'Rainy day activities': 'Actividades para días lluviosos',
      'Romantic sunset viewpoints': 'Miradores románticos al atardecer',
      // Footer
      'Social': 'Redes',
      'Contact Info': 'Info de Contacto',
      'Partners': 'Socios',
      '© 2024 Hotel Al Pelmo Ristorante. All rights reserved.': '© 2024 Hotel Al Pelmo Ristorante. Todos los derechos reservados.',
      'Designed for the Soul of the Dolomites': 'Diseñado para el Alma de las Dolomitas',
    },
  };
  return map[lang] || {};
}

export default LanguageContext;
